import { type TLong } from '../../interface';
import request from '../../tools/request';
import { pathSegment } from '../../tools/utils';
import { type Transaction, type WithApiMixin } from '@decentralchain/ts-types';

/**
 * GET /blocks/headers/seq/{from}/{to}
 * Get block headers at specified heights
 * @param base
 * @param from
 * @param to
 */
export function fetchHeadersSeq(
  base: string,
  from: number,
  to: number,
  options: RequestInit = {},
): Promise<IBlockHeader[]> {
  return request({
    base,
    url: `/blocks/headers/seq/${pathSegment(from)}/${pathSegment(to)}`,
    options,
  });
}

/**
 * GET /blocks/headers/last
 * Last block header
 * @param base
 */
export function fetchHeadersLast(base: string, options: RequestInit = {}): Promise<IBlockHeader> {
  return request({
    base,
    url: `/blocks/headers/last`,
    options,
  });
}

/**
 * GET /blocks/height/{id}
 * Height of a block by its id
 * @param base
 * @param id
 */
export function fetchHeightById(base: string, id: string): Promise<{ height: number }> {
  return request({
    base,
    url: `/blocks/height/${pathSegment(id)}`,
  });
}

/**
 * GET /blocks/headers/at/{height}
 * Block header at height
 * @param base
 * @param height
 */
export function fetchHeadersAt(
  base: string,
  height: number,
  options: RequestInit = {},
): Promise<IBlockHeader> {
  return request({
    base,
    url: `/blocks/headers/at/${pathSegment(height)}`,
    options,
  });
}

/**
 * GET /blocks/headers/{id}
 * Get block at specified height
 * @param base
 * @param height
 */
export function fetchHeadersById(
  base: string,
  id: string,
  options: RequestInit = {},
): Promise<IBlock> {
  return request({
    base,
    url: `/blocks/headers/${pathSegment(id)}`,
    options,
  });
}

/**
 * GET /blocks/at/{height}
 * Get block at specified height
 * @param base
 * @param height
 */
export function fetchBlockAt(
  base: string,
  height: number,
  options: RequestInit = {},
): Promise<IBlock> {
  return request({
    base,
    url: `/blocks/at/${pathSegment(height)}`,
    options,
  });
}

/**
 * GET /blocks/seq/{from}/{to}
 * Block range
 * @param base
 * @param from
 * @param to
 */
export function fetchSeq(
  base: string,
  from: number,
  to: number,
  options: RequestInit = {},
): Promise<IBlock[]> {
  return request({
    base,
    url: `/blocks/seq/${pathSegment(from)}/${pathSegment(to)}`,
    options,
  });
}

/**
 * GET /blocks/{id}
 * Get block by its id
 * @param base
 * @param id
 */
export function fetchBlockById(
  base: string,
  id: string,
  options: RequestInit = {},
): Promise<IBlock> {
  return request({
    base,
    url: `/blocks/${pathSegment(id)}`,
    options,
  });
}

/**
 * GET /blocks/first
 * Get genesis block
 * @param base
 */
export function fetchFirst(base: string, options: RequestInit = {}): Promise<IBlock> {
  return request({
    base,
    url: `/blocks/first`,
    options,
  });
}

/**
 * /blocks/address/{address}/{from}/{to}
 * Get list of blocks generated by specified address
 * @param base
 * @param address
 * @param from
 * @param to
 */
export function fetchBlocksByAddress(
  base: string,
  address: string,
  from: number,
  to: number,
  options: RequestInit = {},
): Promise<IBlock[]> {
  return request({
    base,
    url: `/blocks/address/${pathSegment(address)}/${pathSegment(from)}/${pathSegment(to)}`,
    options,
  });
}

/**
 * GET /blocks/last
 * Last block
 * @param base
 */
export function fetchLast(base: string, options: RequestInit = {}): Promise<IBlock> {
  return request({
    base,
    url: '/blocks/last',
    options,
  });
}

/**
 * GET /blocks/delay/{id}/{blockNum}
 * Average delay in milliseconds between last blockNum blocks starting from block with id
 * @param base
 * @param id
 * @param blockNum
 */
export function fetchDelay(base: string, id: string, blockNum: number): Promise<{ delay: number }> {
  return request({
    base,
    url: `/blocks/delay/${pathSegment(id)}/${pathSegment(blockNum)}`,
  });
}

/**
 * GET /blocks/height
 * @param base
 */
export function fetchHeight(base: string): Promise<{ height: number }> {
  return request({
    base,
    url: '/blocks/height',
  });
}

/**
 * GET /blocks/heightByTimestamp
 * @param base
 */
export function fetchHeightByTimestamp(
  base: string,
  timestamp: number,
  options: RequestInit = {},
): Promise<{ height: number }> {
  return request({
    base,
    url: `/blocks/heightByTimestamp/${pathSegment(timestamp)}`,
    options,
  });
}

export interface IBlockHeader {
  id: string;
  blocksize: number;
  reward: TLong;
  signature: string;
  VRF: string;
  generator: string;
  generatorPublicKey: string;
  version: number;
  reference: string;
  features: string[];
  totalFee: TLong;
  desiredReward: number;
  transactionCount: number;
  timestamp: number;
  height: number;
  'nxt-consensus': {
    'base-target': number;
    'generation-signature': string;
  };
}

export interface IBlock extends IBlockHeader {
  fee: TLong;
  transactions: (Transaction<TLong> & WithApiMixin)[];
}
